<?php

namespace Mrapps\CronjobBundle\Repository;

/**
 * CronLogChiamataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronLogChiamataRepository extends \Doctrine\ORM\EntityRepository
{
}
