<?php

namespace Mrapps\CronjobBundle\Repository;

/**
 * CronLogGruppoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronLogGruppoRepository extends \Doctrine\ORM\EntityRepository
{
}
